spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm_db?serverTimezone=UTC
      username: root
      password: 1234
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
      id-type: auto #???????id?????
  configuration: #??mybatis-plus????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl